### ISSUE TITLE
ResultCode 115 unknown in the client.

### ISSUE THREAD

**Issue by dancetrain** [aerospike/aerospike-client-ruby#22]
```
Aerospike::Exceptions::Aerospike (ResultCode 115 unknown in the client. Please file a github issue.):
  aerospike (1.0.7) lib/aerospike/command/exists_command.rb:47:in `parse_result'
  aerospike (1.0.7) lib/aerospike/command/command.rb:458:in `execute'
  aerospike (1.0.7) lib/aerospike/client.rb:243:in `exists'
```

Server
```
Package: aerospike-server-community
Status: install ok installed
Priority: optional
Section: Databases
Installed-Size: 20388
Maintainer: Aerospike, Inc. <support@aerospike.com>
Architecture: amd64
Version: 3.5.9-1
Depends: libc6 (>= 2.7), logrotate
Conffiles:
 /etc/aerospike/aerospike.conf 170f55275fa2bef984e98b79425731b6
Description: The Aerospike distributed datastore allows fully scalable and reliable data storage with elastic server properties.
Description-md5: 1ce4debd5e2d85b3efb079aa478299ff
```

**Comment by jhecking** [comment]
This issue can happen when using the Aerospike client in a Rails app running within the Passenger application server. Due to the way Passenger spawns multiple application processes from a "pre-loaded" Rails app instance, multiple copies of the client in different application processes can end up sharing one or more TCP connections to the Aerospike cluster.

Please refer to the ["Invalid size for buffer error" thread](https://discuss.aerospike.com/t/invalid-size-for-buffer-error/3291/5) in our user forums for more details and the recommended way to initialize the client when using Passenger.
