### ISSUE TITLE
Digest::Base cannot be directly inherited in Ruby

### ISSUE THREAD

**Issue by werleo** [aerospike/aerospike-client-ruby#45]
We call aerospike in sidekiq workers which requires to have all classes thread safe.

Calling `Aerospike::Key.new(arguments)`

raises `Digest::Base cannot be directly inherited in Ruby`

```
1 gems/aerospike-2.3.0/lib/aerospike/key.rb" line 31 in new
2 gems/aerospike-2.3.0/lib/aerospike/key.rb" line 31 in block in <class:Key>
3 gems/aerospike-2.3.0/lib/aerospike/utils/pool.rb" line 46 in rescue in poll
4 gems/aerospike-2.3.0/lib/aerospike/utils/pool.rb" line 43 in poll
5 gems/aerospike-2.3.0/lib/aerospike/key.rb" line 117 in compute_digest
6 gems/aerospike-2.3.0/lib/aerospike/key.rb" line 61 in initialize
```

From ruby docs we can call Digest classes in thread safe manner:
https://docs.ruby-lang.org/en/2.2.0/Object.html#method-i-Digest

I think it should be done here:
https://github.com/aerospike/aerospike-client-ruby/blob/master/lib/aerospike/key.rb#L31

**Comment by jhecking** [comment]
Interesting! I found similar issues raised in various other projects, e.g. for the [AWS SDK](https://github.com/aws/aws-sdk-ruby/issues/525) or [Chef](https://github.com/chef/chef/issues/1793). But it's not yet clear to me what the right solution is:

* Replace usage of `Digest` with `OpenSSL::Digest` - Are there any downsides to using `OpenSSL::Digest`? Need to clarify why we are using `Digest` on MRI in the first place.
* Use `Digest(:RMD160)` instead of `Digest::RMD160.new` - But looks like `Digest()` was only [made thread-safe](https://github.com/ruby/ruby/commit/c02fa39463a0c6bf698b01bc610135604aca2ff4) in Ruby 2.2, so might not be solving the issue in older versions of Ruby.

Will need to do a bit more research on this.

**Comment by werleo** [comment]
List of not thread safe gems from sidekiq wiki:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#not-thread-safe-gems

I don't know details about OpenSSl::Digest so I am not able to help here.

We use ruby 2.3.3.
